version: '3.4'

services:
  orchestrator-node-1:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
      args:
        - RAFT_BIND=orchestrator-node-1
    networks:
      orchsandbox:
        ipv4_address: 172.20.0.170

  orchestrator-node-2:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
      args:
        - RAFT_BIND=orchestrator-node-2
    networks:
      orchsandbox:
        ipv4_address: 172.20.0.171

  orchestrator-node-3:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
      args:
        - RAFT_BIND=orchestrator-node-3
    networks:
      orchsandbox:
        ipv4_address: 172.20.0.172

  haproxy:
    build:
      context: .
      dockerfile: haproxy/Dockerfile
    command: sh -c '/root/wait-for.sh node1:3306 -- haproxy -f /usr/local/etc/haproxy/haproxy.cfg'
    ports:
      - "8080:8080"
      - "3306:3306"
      - "3307:3307"
      - "80:80"
    networks:
      orchsandbox:
        ipv4_address: 172.20.0.150
    cap_add:
      - NET_ADMIN
      - NET_RAW

  node1:
    image: orch_sandbox_node
    build:
      context: .
      dockerfile: mysql/Dockerfile
    privileged: true
    environment:
      - IS_MASTER=true
      - VIP=172.20.0.200
      - GATEWAY=172.20.0.1
    networks:
      - orchsandbox
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  orchsandbox:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16